[package]
name = "kidns"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = [ "full" ] }
tokio-stream = { version = "0.1", features = [ "net" ] }
tokio-rustls = "0.24"
rustls-pemfile = "1.0"
futures = "0.3"
env_logger = "0.10"
log = "0.4"
dotenv = "0.15"
kube = { version = "0.82", features = ["runtime", "derive", "ws", "rustls-tls"] }
k8s-openapi = { version = "0.18", features = ["v1_23"] }
tower = { version = "0.4.13", features = ["limit"] }
tower-http = { version = "0.4.0", features = ["trace", "decompression-gzip"] }
hyper = { version = "0.14.13", features = ["client", "http1", "stream", "tcp"] }