[package]
name = "kidns"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = [ "full" ] }
tokio-stream = { version = "0.1.12", features = [ "net" ] }
futures = "0.3.28"
env_logger = "0.10"
log = "0.4"
dotenv = "0.15"
kube = { version = "0.82.2", features = ["runtime", "derive", "ws"] }
k8s-openapi = { version = "0.18.0", features = ["v1_26"] }
