dns:
  server:
    # by default will be '8.8.8.8' if not set
    public: 8.8.8.8
    port: 53
    # if empty, dns disabled
    host: 0.0.0.0
    # can be set as 'k8s' to load kubernetes ingress url
    # also can load urls from file('filename')
    # or can be used both, separated by comma(',')
  cache:
    - k8s
    - local_cache.conf
k8s:
  # default(look to ~/.kube/config) or path to yaml file
  # if not set or empty by default is set 'default'
  # if set file in bin directory no need full path
  - config: config
    pod:
      # namespace where is located nginx pods
      namespace: edge-services
      label: app.kubernetes.io/name=ingress-nginx
      port: 443
    # namespace where need to load ingress urls, ex. your app
    ingress-namespace: app-namespace
proxy:
  # if empty, proxy disabled
  host: 0.0.0.0
  # if is needed to access https url, port must be 443,
  # otherwise you'll get error that unable to access https through http
  port: 443
  tls:
  # if not set, local tls disabled
#    cert: testspace/domain.crt
#    key: testspace/domain.key
log-level: info