services:
  kidns:
    container_name: kidns
    image: vitdevelop/kidns:latest
    ports:
      - '53:53/udp'
      - '53:53/tcp'
      - '443:443'
      - '80:80'
    volumes:
      - "./config:/kidns/config:ro"
      - "./config.yaml:/kidns/config.yaml:ro"
