apiVersion: v1
kind: ServiceAccount
metadata:
  name: fw-username
  namespace: app-namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: edge-services
  name: pods-ingress-access-port-forwarder
rules:
- apiGroups: [""]
  resources: ["pods", "pods/portforward"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: app-namespace
  name: ingress-app-access-port-forwarder
rules:
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pods-access
  namespace: edge-services
roleRef:
  kind: Role
  name: pods-ingress-access-port-forwarder
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: fw-username
  namespace: app-namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ingress-access
  namespace: app-namespace
roleRef:
  kind: Role
  name: ingress-app-access-port-forwarder
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: fw-username
  namespace: app-namespace
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: fw-username-token
  namespace: app-namespace
  annotations:
    kubernetes.io/service-account.name: fw-username
